apiVersion: apps/v1
kind: Deployment
metadata:
  name: kompass-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kompass
  template:
    metadata:
      labels:
        app: kompass
    spec:
      containers:
        - name: kompass
          image: kompassmetrics/kompass:latest
---
apiVersion: v1
kind: Service
metadata:
  name: kompass-srv
  labels:
    prometheus: cluster-monitoring
    k8s-app: kube-state-metrics
spec:
  selector:
    app: kompass
  type: ClusterIP
  ports:
    - name: kompass
      protocol: TCP
      port: 3036
      targetPort: 3036

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kompass-rbac
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default